config/routes.rb
Trustthetip::Application.routes.draw do
  
  get "songs/index"

  get "coffee_shops/index"

  get "cocktail_bars/index"

devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    member do 
      post :book
    end
  end

  resources :tiplists 

  resources :tiplistforms

  resources :books, only: [:index]
  resources :restaurants, only: [:index, :show]
  resources :films, only: [:index]
  resources :coffee_shops, only: [:index]
  resources :cocktail_bars, only: [:index]
  resources :songs, only: [:index]

   

  root :to => "home#index"
   

end

app/models/advisable.rb
class Advisable < ActiveRecord::Base
attr_accessible :artist, :author, :location, :name, :type, :tiplist_id, :user_id
has_many :users, :through => :advisable_users
has_many :advisable_users
belongs_to :tiplist
end

app/models/advisable_user.rb
class AdvisableUser < ActiveRecord::Base
  attr_accessible :advisable_id, :user_id
belongs_to :advisable
belongs_to :user
end

app/models/book.rb
class Book < Advisable
  attr_accessible :author, :name
  # has_many :book_users
  # has_many :users, :through => :book_users


end

app/models/book_user.rb
class BookUser < ActiveRecord::Base
  attr_accessible :book_id, :user_id
  belongs_to :user
  belongs_to :book
end

app/models/cocktail_bar.rb
class CocktailBar < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :cocktail_bar_users
  # has_many :cocktail_bar_users
  has_many :advisables, :as => :type
end

app/models/cocktail_bar_user.rb
class CocktailBarUser < ActiveRecord::Base
  attr_accessible :cocktail_bar_id, :user_id
  belongs_to :user
  belongs_to :cocktail_bar
end

app/models/coffee_shop.rb
class CoffeeShop < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :coffee_shop_users
  # has_many :coffee_shops_users
  has_many :advisables, :as => :type
end

app/models/coffee_shop_user.rb
class CoffeeShopUser < ActiveRecord::Base
  attr_accessible :coffee_shop_id, :user_id
  belongs_to :coffee_shop
  belongs_to :user
end

app/models/film.rb
class Film < Advisable
  attr_accessible :name
  # has_many :users, :through => :film_users
  # has_many :film_users
  
end

app/models/film_user.rb
class FilmUser < ActiveRecord::Base
  attr_accessible :film_id, :user_id
  belongs_to :film
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :restaurant_users
  # has_many :restaurant_users
  # geocoded_by :my_cool_geocoding_method
  has_many :advisables, :as => :type

  # def my_cool_geocoding_method
  #    "#{self.location} #{destination.name}"
  # end
end

app/models/restaurant_user.rb
class RestaurantUser < ActiveRecord::Base
  attr_accessible :restaurant_id, :user_id
  belongs_to :restaurant
  belongs_to :user
end

app/models/song.rb
class Song < Advisable
  attr_accessible :artist, :name
  # has_many :users, :through => :song_users
  # has_many :song_users
  
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
  attr_accessible :song_id, :user_id
  belongs_to :song
  belongs_to :user
end

app/models/tiplist.rb
class Tiplist < ActiveRecord::Base
  attr_accessible :name, :advisable_attributes
  has_many :advisables

  def advisable_attributes=(advisable_attributes)
  advisable_attributes.each do |attributes|
    advisables.build(attributes)
  end
end
end

app/models/user.rb
require 'koala'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :image_url, :provider, :uid, :username, :token
  # attr_accessible :title, :body
  has_many :restaurant_users
  has_many :restaurants, :through => :restaurant_users
  has_many :book_users
  has_many :books, :through => :book_users
  has_many :film_users
  has_many :films, :through => :film_users
  has_many :coffee_shop_users
  has_many :coffee_shops, :through => :coffee_shop_users
  has_many :song_users
  has_many :songs, :through => :song_users
  has_many :cocktail_bar_users
  has_many :cocktail_bars, :through => :cocktail_bar_users


#  def self.from_omniauth(auth)
#   where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
#     user.provider = auth.provider
#     user.uid = auth.uid
#     user.username = auth.info.nickname
#     user.token = auth.credentials.token
#     user.email = auth.info['email']
#     user.password = auth.credentials.token
#     user.image_url = auth.info.image

    
#     # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
#     user.save!
#   end
    

# end
# #commented out while testing in the console

# def self.facebook(token)
#   facebook ||= Koala::Facebook::API.new(token)
#   facebook.get_connection('me', 'friends').count
# end

# def facebook
#   facebook ||= Koala::Facebook::API.new(token)
#   # facebook.get_connection('me', 'friends').count
# end

def self.select(current_user)
r = []
    @books = current_user.books
        if @books != nil
        r << @books
    @restaurants = current_user.restaurants
        if @restaurants != nil
            r << @restaurants
    @coffeeshops = current_user.coffee_shops
        if @coffeeshops != nil
            r << @coffeeshops
    @films = current_user.films
        if @films != nil
            r << @films
    @cocktailbars = current_user.cocktail_bars
        if @cocktailbars != nil
            r << @cocktailbars
    @songs = current_user.songs
        if @songs != nil
           
            r << @songs
        end
       end
      end
     end
    end
  end
  return r 

end


# def friend_count
#   facebook.get_connection('me', 'friends').size
# # # rescue koala::Facebook::APIError => e
# # #   logger.info e.to_s
# # #   nil
# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     if user_signed_in?
       # @currentuser = User.facebook(current_user.token)
       @image_url = current_user.image_url
       @user = current_user
      end
   end

   def show
    # @books = current_user.books
    # # binding.pry
    # @restaurants = current_user.restaurants
    # @coffeeshops = current_user.coffee_shops
    # @films = current_user.films
    # @cocktailbars = current_user.cocktail_bars
    # @songs = current_user.songs
    @myinfo = User.select(current_user)
    
    # case 
    # when myinfo[0] != nil
     
    #   @mathilda = myinfo[0][0]
    #   @bookname = @mathilda.name
    #   @sophie = myinfo[0][1]
    #   @sophiename = @sophie.name 
      
    # when myinfo[0] != nil
    #   myinfo[0].each do |x|
    #     @myinfo2 = x.name
    #     binding.pry
    #   end
    # #   puts "Mathilda"
      
        # myinfo[0].each do |x|
        #   binding.pry
        #     @x.name
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tiplist_helper.rb
module TiplistHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="span2 info">
        <div class="mystuff">
          <h3>My stuff</h3>
        </div>
        <div class="box">
          <h4><%=link_to 'My lists', user_path(@user)%></h1>
        </div>
        <div class="box">
          <h4><%=link_to 'Create a new list', new_tiplist_path%></h1>
     </div>
</div>


<div class="span9">
        <div class="span4 expertadvice">
           <h3>Search expert advice.....</h3>
        </div>
</div>


<div class="span9 clearboth">
  <div class="span4">
      <div class="item book">
         <h3><%=link_to 'Books', books_path%></h3>
      </div>
      <div class="item film">
        <h3><%=link_to 'Films', films_path%></h3>
      </div>
      <div class="item music">
        <h3><%=link_to 'Songs', songs_path%></h3>
      </div>
  </div>

  <div class="span4">
    <div class="item cocktailbar">
      <h3><%=link_to 'Cocktail Bars', cocktail_bars_path%></h3>
    </div>
    <div class="item restaurant">
      <h3><%=link_to 'Restaurants', restaurants_path%></h3>
    </div>
    <div class="item coffeeshop">
      <h3><%=link_to 'Coffee Shop', coffee_shops_path%></h3>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="selectcategory">
  <h1>Create a new list</h1>

<div class="btn-group">
  <button class="btn dropdown-toggle" data-toggle="dropdown">
    Select a list category <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
   <li><a href="#" class="songform">Songs</a></li>
   <li><a href="#" class="restaurantform">Restaurants</a></li>
   <li><a href="#" class="coffeeshopform">Coffee Shops</a></li>
   <li><a href="#" class="filmform">Films</a></li>
   <li><a href="#" class="cocktailbarform">CocktailBars</a></li>
   <li><a href="#" class="bookform">Books</a></li>
 </ul>
</div>
</div>

<% for book in @books %>
  <div class="mainbook">
    <%= form_for @books, :url => book_user_path(@user.id), :method => 'POST' do |f| %>

      <div class="bookform">
        <h5>Book</h5>
        <%= f.text_field :name, :placeholder => 'Book title' %><br>
        <%= f.text_field :author, :placeholder => 'Book author' %>
        <button class="addbook">Add another book</button>
      </div>
      <%= f.submit "Create", :class => 'btn' %>
    <% end %>
  </div>
<% end %>

<% for restaurant in @restaurants %>
  <div class="mainrestaurant">
    <%= form_for @restaurants, :url => {:controller => :users, :action => "create", :method => :post } do |f| %>

    <div class="restaurantform">
      <h5>Restaurant</h5>
      <%= f.text_field :name, :placeholder => 'Restaurant name' %><br>
      <%= f.text_field :location, :placeholder => 'Address' %><br>
  </div>
    <%= f.submit "Create", :class => 'btn' %>
  <%end%>
 </div>
<%end%>


<div class="mainfilm">
<%= form_for @films, :url => {:controller => :users, :action => "create", :method => :post } do |f| %>

<div class="filmform">
  <h5>Films</h5>
  <%= f.text_field :name, :placeholder => 'Film name' %><br>
</div>
  <%= f.submit "Create", :class => 'btn' %>
<% end %>
</div>

<div class="mainsong">
<%= form_for @songs, :url => {:controller => :users, :action => "create", :method => :post } do |f| %>

<div class="songform">
  <h5>Songs</h5>
  <%= f.text_field :name, :placeholder => 'Song name' %><br>
  <%= f.text_field :artist, :placeholder => 'artist' %><br>
</div>
  <%= f.submit "Create", :class => 'btn' %>
<% end %>
</div>

<div class="maincoffeeshop">
<%= form_for @coffeeshops, :url => {:controller => :users, :action => "create", :method => :post } do |f| %>

<div class="coffeeshopform">
  <h5>Coffee Shop</h5>
  <%= f.text_field :name, :placeholder => 'name' %><br>
  <%= f.text_field :location, :placeholder => 'location' %><br>
</div>
  <%= f.submit "Create", :class => 'btn' %>
<% end %>
</div>

<div class="maincocktailbar">
<%= form_for @cocktailbars, :url => {:controller => :users, :action => "create", :method => :post } do |f| %>

<div class="cocktailbarform">
  <h5>Cocktail Bars</h5>
  <%= f.text_field :name, :placeholder => 'name' %><br>
  <%= f.text_field :location, :placeholder => 'location' %><br>
</div>
  <%= f.submit "Create", :class => 'btn' %>
<% end %>
</div>



           

app/views/users/show.html.erb
<!-- <div class="mylists">
  <h1> My Lists </h1>
</div> -->

<div class="showlists">
    <% @last_type = nil %>
    <% @myinfo.each_with_index do |advice, i| %>
    <%#binding.pry%>
        <% if @last_type == nil || @last_type != advice.class %>
          <div class="span4 userlist">
            <%#= render :partial => "advice/#{advice.class.to_s.downcase}", :locals => { :advice => advice } %>
            <h3> <%= @lasttype = advice.class %> </h3>
        <%end%>
    <%= advice.name %> <br>

      <% if @myinfo[i + 1].class != advice.class %>
      
  </div>
  <% end %>
  <% @last_type = advice.class %>
  <% end %>

  