config/routes.rb
Trustthetip::Application.routes.draw do
  
  get "songs/index"

  get "coffee_shops/index"

  get "cocktail_bars/index"

devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    member do 
      post :book
    end
  end

  resources :tiplists 

  resources :tiplistforms

  resources :books, only: [:index]
  resources :restaurants, only: [:index, :show]
  resources :films, only: [:index]
  resources :coffee_shops, only: [:index]
  resources :cocktail_bars, only: [:index]
  resources :songs, only: [:index]

   

  root :to => "home#index"
   

end

app/models/advisable.rb
class Advisable < ActiveRecord::Base
attr_accessible :artist, :author, :location, :name, :type, :tiplist_id, :user_id
has_many :users, :through => :advisable_users
has_many :advisable_users
belongs_to :tiplist
end

app/models/advisable_user.rb
class AdvisableUser < ActiveRecord::Base
  attr_accessible :advisable_id, :user_id
belongs_to :advisable
belongs_to :user
end

app/models/book.rb
class Book < Advisable
  attr_accessible :author, :name
  # has_many :book_users
  # has_many :users, :through => :book_users


end

app/models/book_user.rb
class BookUser < ActiveRecord::Base
  attr_accessible :book_id, :user_id
  belongs_to :user
  belongs_to :book
end

app/models/cocktail_bar.rb
class CocktailBar < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :cocktail_bar_users
  # has_many :cocktail_bar_users
  has_many :advisables, :as => :type
end

app/models/cocktail_bar_user.rb
class CocktailBarUser < ActiveRecord::Base
  attr_accessible :cocktail_bar_id, :user_id
  belongs_to :user
  belongs_to :cocktail_bar
end

app/models/coffee_shop.rb
class CoffeeShop < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :coffee_shop_users
  # has_many :coffee_shops_users
  has_many :advisables, :as => :type
end

app/models/coffee_shop_user.rb
class CoffeeShopUser < ActiveRecord::Base
  attr_accessible :coffee_shop_id, :user_id
  belongs_to :coffee_shop
  belongs_to :user
end

app/models/film.rb
class Film < Advisable
  attr_accessible :name
  # has_many :users, :through => :film_users
  # has_many :film_users
  
end

app/models/film_user.rb
class FilmUser < ActiveRecord::Base
  attr_accessible :film_id, :user_id
  belongs_to :film
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < Advisable
  attr_accessible :latitude, :location, :longitude, :name
  # has_many :users, :through => :restaurant_users
  # has_many :restaurant_users
  # geocoded_by :my_cool_geocoding_method
  has_many :advisables, :as => :type

  # def my_cool_geocoding_method
  #    "#{self.location} #{destination.name}"
  # end
end

app/models/restaurant_user.rb
class RestaurantUser < ActiveRecord::Base
  attr_accessible :restaurant_id, :user_id
  belongs_to :restaurant
  belongs_to :user
end

app/models/song.rb
class Song < Advisable
  attr_accessible :artist, :name
  # has_many :users, :through => :song_users
  # has_many :song_users
  
end

app/models/song_user.rb
class SongUser < ActiveRecord::Base
  attr_accessible :song_id, :user_id
  belongs_to :song
  belongs_to :user
end

app/models/tiplist.rb
class Tiplist < ActiveRecord::Base
  attr_accessible :name, :advisable_attributes
  has_many :advisables

  def advisable_attributes=(advisable_attributes)
  advisable_attributes.each do |attributes|
    advisables.build(attributes)
  end
end
end

app/models/user.rb
require 'koala'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :image_url, :provider, :uid, :username, :token
  # attr_accessible :title, :body
  has_many :restaurant_users
  has_many :restaurants, :through => :restaurant_users
  has_many :book_users
  has_many :books, :through => :book_users
  has_many :film_users
  has_many :films, :through => :film_users
  has_many :coffee_shop_users
  has_many :coffee_shops, :through => :coffee_shop_users
  has_many :song_users
  has_many :songs, :through => :song_users
  has_many :cocktail_bar_users
  has_many :cocktail_bars, :through => :cocktail_bar_users


#  def self.from_omniauth(auth)
#   where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
#     user.provider = auth.provider
#     user.uid = auth.uid
#     user.username = auth.info.nickname
#     user.token = auth.credentials.token
#     user.email = auth.info['email']
#     user.password = auth.credentials.token
#     user.image_url = auth.info.image

    
#     # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
#     user.save!
#   end
    

# end
# #commented out while testing in the console

# def self.facebook(token)
#   facebook ||= Koala::Facebook::API.new(token)
#   facebook.get_connection('me', 'friends').count
# end

# def facebook
#   facebook ||= Koala::Facebook::API.new(token)
#   # facebook.get_connection('me', 'friends').count
# end

def self.select(current_user)
r = []
    @books = current_user.books
        if @books != nil
        r << @books
    @restaurants = current_user.restaurants
        if @restaurants != nil
            r << @restaurants
    @coffeeshops = current_user.coffee_shops
        if @coffeeshops != nil
            r << @coffeeshops
    @films = current_user.films
        if @films != nil
            r << @films
    @cocktailbars = current_user.cocktail_bars
        if @cocktailbars != nil
            r << @cocktailbars
    @songs = current_user.songs
        if @songs != nil
           
            r << @songs
        end
       end
      end
     end
    end
  end
  return r 

end


# def friend_count
#   facebook.get_connection('me', 'friends').size
# # # rescue koala::Facebook::APIError => e
# # #   logger.info e.to_s
# # #   nil
# end

end

app/controllers/tiplists_controller.rb
class TiplistsController < ApplicationController
   def new
    @tiplist = Tiplist.new
    10.times { @tiplist.advisables.build}
    # @tiplist.advisables = [Book.new, Restaurant.new, CoffeeShop.new, Song.new, CocktailBar.new, Film.new]
   end 

   def create
    @tiplist = Tiplist.new(params[:tiplist])
    # binding.pry
    @tiplist.save!
   end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tiplist_helper.rb
module TiplistHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tiplists/_tiplist.html.erb
<%= fields_for "tiplist[advisable_attributes][]", advisable do |advisable_form| %>
        <p>
          Name: <%= advisable_form.text_field :name %>
          Author: <%= advisable_form.text_field :author %>
          Artist: <%= advisable_form.text_field :artist %>
          Location: <%= advisable_form.text_field :location %>
        </p>
      <% end %>

app/views/tiplists/_tiplists.html.erb
<div class="advisable">
<%= fields_for "tiplist[advisable_attributes][]", @advisable do |advisable_form| %>
  <p>
    Advisable: <%= advisable_form.text_field :name %>
    Advisable: <%= advisable_form.text_field :author %>
    Advisable: <%= advisable_form.text_field :artist %>
    Advisable: <%= advisable_form.text_field :location %>
    <%#= link_to_function "remove", "$(this).up('.task').remove()" %>
  </p>
<% end %>
</div>

app/views/tiplists/new.html.erb
<h3>Create a new tiplist</h3>

<%#=form_tag tiplistforms_path, :remote => true do |f| %>
  <%#= select(:tiplist, :name, [['Book', 'Book'], ['Song', 'Song'], ['CoffeeShop', 'CoffeeShop'], ['CocktailBar', 'CocktailBar'], ['Restaurant', 'Restaurant'], ['Film', 'Film']]) %> 
 <!--  <p><%#= submit_tag "Choose category" %></p> -->
<%#end%>

<%= form_for :tiplist, :url => tiplists_path, :action => :create do |f| %>
  <p>
    Name: <%= select(:tiplist, :name, [['Book', 'Book', :class=>'bookselect'], ['Song', 'Song', :class=>'songselect'], ['CoffeeShop', 'CoffeeShop', :class=>'coffeeshopselect'], ['CocktailBar', 'CocktailBar', :class=>'cocktailbarselect'], ['Restaurant', 'Restaurant', :class=>'restaurantselect'], ['Film', 'Film', :class=>'filmselect']]) %> 
  </p>
   
  <div class="container">
      <% for @advisable in @tiplist.advisables %>

        <div class="coffeerestaurantcocktailform">
            <%= fields_for "tiplist[advisable_attributes][]", @advisable do |advisable_form| %>
              <p>
                Name: <%= advisable_form.text_field :name %>
                Artist: <%= advisable_form.text_field :artist %>
                Author: <%= advisable_form.text_field :author %>
                Location: <%= advisable_form.text_field :location %>
              </p>
            <% end %>
        </div>

       <!--  <div class="filmform">
            <%#= fields_for "tiplist[advisable_attributes][]", @advisable do |advisable_form| %>
              <p>
                Name: <%#= advisable_form.text_field :name %>
              </p>
            <%# end %>
        </div>

        <div class="bookform">
            <%#= fields_for "tiplist[advisable_attributes][]", @advisable do |advisable_form| %>
              <p>
                Name: <%#= advisable_form.text_field :name %>
                Author: <%#= advisable_form.text_field :author %>
              </p>
            <%# end %>
        </div>

          <div class="songform">
            <%#= fields_for "tiplist[advisable_attributes][]", @advisable do |advisable_form| %>
              <p>
                Name: <%#= advisable_form.text_field :name %>
                Artist: <%#= advisable_form.text_field :artist %>
              </p>
            <%# end %>
        </div>

      <%# end %>
  </div> -->
<% end %>
<p><%= submit_tag "Create Tiplist" %></p>
<% end %>

app/views/tiplists/tiplist.js.erb
var category = ("<%= escape_javascript(@advisablescategory) %>");

$('.rendereddiv').append('Hello');